import { SplitCheck } from "../../models/splitCheck";

export const fakeSplitCheckResults: SplitCheck[] = [
  {
    name: "Albert",
    items: [
      {
        id: "James West",
        name: "James West",
        quantity: 1,
        unitPrice: 16.95,
        totalPrice: 16.95,
        buyers: [new Set<string>(["Albert"])],
      },
      {
        id: "Caesar Salad",
        name: "Caesar Salad",
        quantity: 1,
        unitPrice: 5.5,
        totalPrice: 5.5,
        buyers: [new Set<string>(["Albert"])],
      },
      {
        id: "Tots-2",
        name: "Tots",
        quantity: 1,
        unitPrice: 3.95,
        totalPrice: 3.95,
        buyers: [new Set<string>(["Albert"])],
      },
      {
        id: "Processing Fee",
        name: "Processing Fee",
        quantity: 1,
        unitPrice: 4.51,
        totalPrice: 4.51,
        buyers: [new Set<string>(["Albert", "Angus", "Justin", "Justin L.", "Vincent"])],
        note: "Shared with Angus, Justin, Justin L., Vincent",
      },
    ],
    tax: 2.66,
    tip: 4.34,
    subTotalPrice: 27.3,
    totalPrice: 34.3,
  },
  {
    name: "Angus",
    items: [
      {
        id: "Bahn, James Bahn",
        name: "Bahn, James Bahn",
        quantity: 1,
        unitPrice: 16.95,
        totalPrice: 16.95,
        buyers: [new Set<string>(["Angus"])],
      },
      {
        id: "Fish & Fries",
        name: "Fish & Fries",
        quantity: 1,
        unitPrice: 14.95,
        totalPrice: 14.95,
        buyers: [new Set<string>(["Angus"])],
      },
      {
        id: "Processing Fee",
        name: "Processing Fee",
        quantity: 1,
        unitPrice: 4.51,
        totalPrice: 4.51,
        buyers: [new Set<string>(["Albert", "Angus", "Justin", "Justin L.", "Vincent"])],
        note: "Shared with Albert, Justin, Justin L., Vincent",
      },
    ],
    tax: 3.2,
    tip: 5.22,
    subTotalPrice: 32.8,
    totalPrice: 41.22,
  },
  {
    name: "Justin",
    items: [
      {
        id: "Shroom & Truffle Shuffle",
        name: "Shroom & Truffle Shuffle",
        quantity: 1,
        unitPrice: 15.95,
        totalPrice: 15.95,
        buyers: [new Set<string>(["Justin"])],
      },
      {
        id: "Processing Fee",
        name: "Processing Fee",
        quantity: 1,
        unitPrice: 4.51,
        totalPrice: 4.51,
        buyers: [new Set<string>(["Albert", "Angus", "Justin", "Justin L.", "Vincent"])],
        note: "Shared with Albert, Angus, Justin L., Vincent",
      },
    ],
    tax: 1.64,
    tip: 2.68,
    subTotalPrice: 16.85,
    totalPrice: 21.77,
  },
  {
    name: "Justin L.",
    items: [
      {
        id: "Crispy Fried Chicken",
        name: "Crispy Fried Chicken",
        quantity: 1,
        unitPrice: 15.95,
        totalPrice: 15.95,
        buyers: [new Set<string>(["Justin L."])],
      },
      {
        id: "Tots",
        name: "Tots",
        quantity: 1,
        unitPrice: 2,
        totalPrice: 2,
        buyers: [new Set<string>(["Justin L."])],
      },
      {
        id: "Processing Fee",
        name: "Processing Fee",
        quantity: 1,
        unitPrice: 4.51,
        totalPrice: 4.51,
        buyers: [new Set<string>(["Albert", "Angus", "Justin", "Justin L.", "Vincent"])],
        note: "Shared with Albert, Angus, Justin, Vincent",
      },
    ],
    tax: 1.84,
    tip: 3,
    subTotalPrice: 18.85,
    totalPrice: 23.69,
  },
  {
    name: "Vincent",
    items: [
      {
        id: "Vanilla Shake",
        name: "Vanilla Shake",
        quantity: 1,
        unitPrice: 7.95,
        totalPrice: 7.95,
        buyers: [new Set<string>(["Vincent"])],
      },
      {
        id: "Processing Fee",
        name: "Processing Fee",
        quantity: 1,
        unitPrice: 4.51,
        totalPrice: 4.51,
        buyers: [new Set<string>(["Albert", "Angus", "Justin", "Justin L.", "Vincent"])],
        note: "Shared with Albert, Angus, Justin, Justin L.",
      },
    ],
    tax: 2.51,
    tip: 4.1,
    subTotalPrice: 25.8,
    totalPrice: 32.41,
  },
];
